import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { AuthProvider } from "@/app/auth_provider/AuthProvider";
import "./globals.css";
import { initializeFirebaseApp } from './firebase'
import { getApp } from "firebase/app";
import { auth } from "./firebase";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode; }>) {
  initializeFirebaseApp();
  console.log("hello")
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthProvider>{children}</AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
