# Generated by Django 5.0.6 on 2024-05-16 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SNS", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contest_post",
            old_name="user",
            new_name="user_id",
        ),
    ]
