# Generated by Django 5.0.4 on 2024-05-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0002_remove_post_content_post_text_alter_message_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
