# Generated by Django 5.0.3 on 2024-05-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontMind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dont_minds', to='SNS.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNS.user')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'post')},
            },
        ),
    ]
