# Generated by Django 5.0.3 on 2024-05-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0008_alter_dontmind_user_alter_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learneds', to='SNS.post')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'post')},
            },
        ),
    ]
