# Generated by Django 5.0.3 on 2024-05-17 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0010_contest_contest_post_remove_room_users_vote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=1000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='SNS.post')),
            ],
        ),
    ]
