# Generated by Django 5.0.3 on 2024-05-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0011_aisolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisolution',
            name='solution',
        ),
        migrations.AddField(
            model_name='aisolution',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
