# Generated by Django 5.0.6 on 2024-05-17 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SNS", "0012_remove_aisolution_solution_aisolution_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest_post",
            name="created_at",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
