# Generated by Django 5.0.6 on 2024-05-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SNS", "0013_contest_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="SNS.contest_post",
            ),
        ),
    ]
