# Generated by Django 5.0.6 on 2024-05-18 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SNS", "0015_rename_user_id_contest_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="available",
            field=models.BooleanField(
                default=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contest",
            name="deadline",
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contest",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
