# Generated by Django 5.0.6 on 2024-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SNS", "0016_contest_available_contest_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="created_at",
            field=models.CharField(max_length=50),
        ),
    ]
