# Generated by Django 5.0.6 on 2024-05-18 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SNS", "0017_alter_contest_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="available",
        ),
    ]
