# Generated by Django 5.0.3 on 2024-05-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0018_remove_contest_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_post',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dontmind',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='learned',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='匿名ユーザー', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
