# Generated by Django 5.0.6 on 2024-05-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SNS", "0018_remove_contest_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
