# Generated by Django 5.0.3 on 2024-05-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0019_alter_contest_post_user_alter_dontmind_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
